### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by BUNO19** [FicHub/fichub-cli#19]
Hi! When I tried to download a fic, it couldn't work.
`fichub_cli -u https://www.fanfiction.net/s/6340084/1/Life-s-Little-Surprises --format epub`

`fichub_cli -u https://www.fanfiction.net/s/6340084/1/Life-s-Little-Surprises`

The following is the feedback:
```
 0%|                        | 0/1, ?file/s, ETA: ?
Traceback (most recent call last):
  File "/root/venv/bin/fichub_cli", line 8, in <module>
    sys.exit(app())
  File "/shared-libs/python3.9/py/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/shared-libs/python3.9/py/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/shared-libs/python3.9/py/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/shared-libs/python3.9/py/lib/python3.9/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/shared-libs/python3.9/py/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/shared-libs/python3.9/py/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/shared-libs/python3.9/py/lib/python3.9/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/root/venv/lib/python3.9/site-packages/fichub_cli/cli.py", line 157, in default
    fic.get_fic_with_url(url)
  File "/root/venv/lib/python3.9/site-packages/fichub_cli/utils/fetch_data.py", line 247, in get_fic_with_url
    self.exit_status, _ = save_data(
  File "/root/venv/lib/python3.9/site-packages/fichub_cli/utils/processing.py", line 94, in save_data
    hash_flag = check_hash(ebook_file, cache_hash)
  File "/root/venv/lib/python3.9/site-packages/fichub_cli/utils/processing.py", line 139, in check_hash
    with open(ebook_file, 'rb') as file:
OSError: [Errno 116] Stale file handle: 'Life_s_Little_Surprises_by_J_S_Jamesbrooke-lybfin9w.epub'
```

**Comment by arzkar** [comment]
I couldnt replicate the issue. Can you retry and see if it works for you?
![image](https://user-images.githubusercontent.com/70950611/209477153-84b1e7e7-d88c-4c6c-a3e8-a3ff36223d67.png)

**Comment by BUNO19** [comment]
Thank you!
I added quote, and it works fine now.
`fichub_cli -u "https://www.fanfiction.net/s/6340084/1/Life-s-Little-Surprises"`
